{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "paperclip.fullname" . }}-vault-store
  labels:
    {{- include "paperclip.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.address | quote }}
      path: {{ .Values.vault.mount | quote }}
      version: "v2"
      {{- if .Values.vault.tlsSkipVerify }}
      caBundle: ""
      {{- end }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.authPath | quote }}
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.serviceAccount | quote }}
            namespace: {{ .Release.Namespace }}
{{- end }}
